### ISSUE TITLE
[Bug]: Keyboard navigation in blogs page doesn't auto-scroll to selected items outside viewport

### ISSUE THREAD

**Issue by ParasSolanki** [nexxeln/nexxel.dev#47]
When using up/down arrow keys to navigate through blog posts, the page does not automatically scroll to keep the selected item in view when it moves outside the visible window area.

[screen-capture (70).webm](https://github.com/user-attachments/assets/46ecd30d-73f8-40c5-b3e2-766d6081e9d2)

**Comment by nexxeln** [comment]
will fix soon

**Comment by nexxeln** [comment]
fixed in 0511293528a72b9b278193585e2c39db64571efd
